# WASM runtime bootstrap package
# This is a meta-package that contains the browser runtime setup.
# It does not compile any code — it provides the Emscripten runtime configuration.

TERMUX_PKG_HOMEPAGE=https://github.com/ghshhf/glibc-packages
TERMUX_PKG_DESCRIPTION="glibc-packages WebAssembly runtime bootstrap — provides Emscripten runtime environment configuration"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@ghshhf"
TERMUX_PKG_VERSION=1.0.0
TERMUX_PKG_DEPENDS=""
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_PLATFORM="browser"  # Only buildable for browser/WASM target

termux_step_make() {
    # No compilation needed — this is a bootstrap package
    # The browser runtime is built separately via npm in browser-runtime/
    :
}

termux_step_make_install() {
    # Create Emscripten runtime configuration directory
    mkdir -p "${TERMUX_PREFIX}/share/emscripten-runtime"

    # Generate Emscripten runtime config
    cat > "${TERMUX_PREFIX}/share/emscripten-runtime/config.json" <<-CONFIGEOF
{
  "runtime": "emscripten",
  "version": "${TERMUX_PKG_VERSION}",
  "wasm_target": "wasm32-unknown-emscripten",
  "features": {
    "filesystem": true,
    "threads": true,
    "simd": false,
    "memory64": false
  },
  "memory": {
    "initial": 67108864,
    "maximum": 536870912,
    "stack": 262144
  },
  "exports": {
    "runtime_methods": [
      "callMain", "FS", "PATH", "ERRNO_CODES",
      "TTY", "DYNAMIC_CALLS", "stackAlloc",
      "stackSave", "stackRestore", "getValue", "setValue"
    ],
    "functions": ["_malloc", "_free", "_main"]
  },
  "optimization": {
    "level": "O2",
    "lto": false,
    "closure": false
  }
}
CONFIGEOF

    # Generate Emscripten toolchain file for cmake
    mkdir -p "${TERMUX_PREFIX}/share/cmake/toolchains"
    cat > "${TERMUX_PREFIX}/share/cmake/toolchains/Emscripten.cmake" <<-CMAKEEOF
# Emscripten CMake toolchain file
# Generated by glibc-packages WASM runtime bootstrap

set(CMAKE_SYSTEM_NAME Emscripten)
set(CMAKE_SYSTEM_PROCESSOR wasm32)
set(CMAKE_CROSSCOMPILING TRUE)

set(CMAKE_C_COMPILER emcc)
set(CMAKE_CXX_COMPILER em++)
set(CMAKE_AR emar)
set(CMAKE_RANLIB emranlib)
set(CMAKE_LINKER emcc)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_C_FLAGS "-O2 -fPIC -D__EMSCRIPTEN__=1 -DWASM_BROWSER=1")
set(CMAKE_CXX_FLAGS "-O2 -fPIC -D__EMSCRIPTEN__=1 -DWASM_BROWSER=1")
set(CMAKE_EXE_LINKER_FLAGS "-s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s FILESYSTEM=1")
set(CMAKE_SHARED_LINKER_FLAGS "-s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s FILESYSTEM=1")
CMAKEEOF

    echo "[WASM Runtime] 配置文件已安装到 ${TERMUX_PREFIX}/share/emscripten-runtime/"
}

termux_step_post_make_install() {
    echo ""
    echo "============================================"
    echo " WASM Runtime Bootstrap v${TERMUX_PKG_VERSION}"
    echo "============================================"
    echo " 目标:       wasm32-unknown-emscripten"
    echo " 文件系统:   已启用 (MEMFS/OPFS)"
    echo " 线程:       已启用 (Web Workers + SAB)"
    echo " 内存:       64MB ~ 512MB"
    echo "============================================"
    echo ""
    echo " 在浏览器中使用:"
    echo "   npm install @glibc-packages/browser-runtime"
    echo "   import { GlibcRuntime } from '@glibc-packages/browser-runtime'"
    echo "   GlibcRuntime.init()"
    echo ""
    echo " 构建 WASM 包:"
    echo "   ./build-wasm.sh gpkg/zlib"
    echo "============================================"
}
